### ISSUE TITLE
DHT22 and open-drain output pin

### ISSUE THREAD

**Issue by holotrack** [riscv-rust/riscv-rust-quickstart#22]
Im trying to use HiFive rev b board with DHT22 sensor. It needs "open-drain" output option to work. I asked on Matrix - Rust Embedded channel and what i get from there its not supported by this chip or library. As solution for this they gave me as example this link:

https://github.com/rp-rs/rp-hal/blob/main/rp2040-hal/examples/dht11.rs#L55-L88

"At a lower level, you could set input_en=1, output_val=0, pue=1 and then set output_en=1 to actively pull the line down, output_en=0 to pull it up using the weak pull-up resistor, and read input_val to read back the DHT response. But it seems like that mode is not implemented by the HAL. (Same situation as with the RP2040 and its HAL)"

Please could you update your library with such feature? To make it more useful for others.

**Comment by almindor** [comment]
NOTE: this is an issue with the [e310x-hal](https://github.com/riscv-rust/e310x-hal). As a first step could you please move/copy this issue there? I'm currently out of country but can have a look later in September. @Disasm might also have ideas on this as I'm not too familiar with this area.

**Comment by almindor** [comment]
closing in favour of [the hal issue](https://github.com/riscv-rust/e310x-hal/issues/46)
